<?php

namespace ContainerVxz7rY3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EmployeRepository' shared autowired service.
     *
     * @return \App\Repository\EmployeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EmployeRepository'] = new \App\Repository\EmployeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
