<?php

namespace ContainerVxz7rY3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateEntitiesCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\GenerateEntitiesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\GenerateEntitiesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate:entities', [], 'Automatically generates entity classes from the database schema', false, #[\Closure(name: 'App\\Command\\GenerateEntitiesCommand')] fn (): \App\Command\GenerateEntitiesCommand => ($container->privates['App\\Command\\GenerateEntitiesCommand'] ?? $container->load('getGenerateEntitiesCommandService')));
    }
}
