<?php

namespace ContainerGo3lC9J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3oB9lRWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3oB9lRW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3oB9lRW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'quizApiClient' => ['privates', 'App\\Service\\QuizApiClient', 'getQuizApiClientService', true],
        ], [
            'quizApiClient' => 'App\\Service\\QuizApiClient',
        ]);
    }
}
