<?php

namespace ContainerGo3lC9J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q3ukLepService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q3ukLep' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q3ukLep'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'permis' => ['privates', '.errored..service_locator.q3ukLep.App\\Entity\\Permis', NULL, 'Cannot autowire service ".service_locator.q3ukLep": it needs an instance of "App\\Entity\\Permis" but this type has been excluded in "config/services.yaml".'],
            'quizRepository' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
        ], [
            'entityManager' => '?',
            'permis' => 'App\\Entity\\Permis',
            'quizRepository' => 'App\\Repository\\QuizRepository',
        ]);
    }
}
