<?php

namespace ContainerGo3lC9J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPermis2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q3ukLep.App\Entity\Permis' shared service.
     *
     * @return \App\Entity\Permis
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.q3ukLep": it needs an instance of "App\\Entity\\Permis" but this type has been excluded in "config/services.yaml".');
    }
}
