<?php

namespace ContainerVxz7rY3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_IL0PUj3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.iL0PUj3' shared service.
     *
     * @return \KnpU\OAuth2ClientBundle\Client\ClientRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\GoogleController::connectAction()": the $clientRegistry argument is type-hinted with the non-existent class or interface: "KnpU\\OAuth2ClientBundle\\Client\\ClientRegistry".');
    }
}
