<?php

namespace ContainerVxz7rY3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\EditType' shared autowired service.
     *
     * @return \App\Form\EditType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\EditType'] = new \App\Form\EditType();
    }
}
