<?php

namespace ContainerVxz7rY3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateEntitiesCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\GenerateEntitiesCommand' shared autowired service.
     *
     * @return \App\Command\GenerateEntitiesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\GenerateEntitiesCommand'] = $instance = new \App\Command\GenerateEntitiesCommand(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()));

        $instance->setName('app:generate:entities');
        $instance->setDescription('Automatically generates entity classes from the database schema');

        return $instance;
    }
}
