hwi_oauth:
    firewall_names: [main]  # Should match your security firewall
    resource_owners:
        google:
            type:          google
            client_id:     "%env(OAUTH_GOOGLE_CLIENT_ID)%"
            client_secret: "%env(OAUTH_GOOGLE_CLIENT_SECRET)%"
            scope:         "email profile"  # Requested permissions
            options:
                access_type: online  # Optional