security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # 🔄 Chargement depuis la base de données avec l'entité App\Entity\User
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\GoogleAuthenticator

            # 🔐 Authenticator pour Google (personnalisé)   
            # 🔐 Authenticator pour Google (personnalisé
            

            # 🔐 Authenticator pour Google (personnalisé)
            logout:
                path: app_logout
                target: app_home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 7 jours


      
