<?php

namespace ContainerFaPmHqL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizApiClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\QuizApiClient' shared autowired service.
     *
     * @return \App\Service\QuizApiClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'QuizApiClient.php';

        return $container->privates['App\\Service\\QuizApiClient'] = new \App\Service\QuizApiClient(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
