<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxz7rY3\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxz7rY3/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVxz7rY3.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVxz7rY3\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerVxz7rY3\App_KernelProdContainer([
    'container.build_hash' => 'Vxz7rY3',
    'container.build_id' => '9c46d1a9',
    'container.build_time' => 1744452060,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxz7rY3');
