<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHa0n4Nm\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHa0n4Nm/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHa0n4Nm.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHa0n4Nm\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHa0n4Nm\App_KernelProdContainer([
    'container.build_hash' => 'Ha0n4Nm',
    'container.build_id' => 'd5722a25',
    'container.build_time' => 1745749357,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHa0n4Nm');
