<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oz1C83WService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.oz1C83W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oz1C83W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'permisRepository' => ['privates', 'App\\Repository\\PermisRepository', 'getPermisRepositoryService', true],
            'twilioService' => ['privates', 'App\\Service\\TwilioWhatsappService', 'getTwilioWhatsappServiceService', true],
        ], [
            'permisRepository' => 'App\\Repository\\PermisRepository',
            'twilioService' => 'App\\Service\\TwilioWhatsappService',
        ]);
    }
}
