<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q5g0ToOService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.q5g0ToO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q5g0ToO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'permis' => ['privates', '.errored..service_locator.q5g0ToO.App\\Entity\\Permis', NULL, 'Cannot autowire service ".service_locator.q5g0ToO": it needs an instance of "App\\Entity\\Permis" but this type has been excluded in "config/services.yaml".'],
        ], [
            'permis' => 'App\\Entity\\Permis',
        ]);
    }
}
