<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Console_Command_SchedulerDebug_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.console.command.scheduler_debug.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.console.command.scheduler_debug.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('debug:scheduler', [], 'List schedules and their recurring messages', false, #[\Closure(name: 'console.command.scheduler_debug', class: 'Symfony\\Component\\Scheduler\\Command\\DebugCommand')] fn (): \Symfony\Component\Scheduler\Command\DebugCommand => ($container->privates['console.command.scheduler_debug'] ?? $container->load('getConsole_Command_SchedulerDebugService')));
    }
}
