<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_FWSClS0Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.FWSClS0' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.FWSClS0'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Symfony\Component\Scheduler\Messenger\ServiceCallMessageHandler(($container->privates['.service_locator.Xbsa8iG'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], []))), []);
    }
}
