<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckExpiredPermisCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CheckExpiredPermisCommand' shared autowired service.
     *
     * @return \App\Command\CheckExpiredPermisCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CheckExpiredPermisCommand'] = $instance = new \App\Command\CheckExpiredPermisCommand(($container->privates['App\\Repository\\PermisRepository'] ?? $container->load('getPermisRepositoryService')), ($container->privates['App\\Service\\TwilioWhatsappService'] ??= new \App\Service\TwilioWhatsappService()));

        $instance->setName('app:check-expired-permis');
        $instance->setDescription('Checks for expired permits and sends WhatsApp notifications');

        return $instance;
    }
}
