<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarteGriseRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CarteGriseRepository' shared autowired service.
     *
     * @return \App\Repository\CarteGriseRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CarteGriseRepository'] = new \App\Repository\CarteGriseRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
