<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckExpiredPermisCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\CheckExpiredPermisCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\CheckExpiredPermisCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:check-expired-permis', [], 'Checks for expired permits and sends WhatsApp notifications', false, #[\Closure(name: 'App\\Command\\CheckExpiredPermisCommand')] fn (): \App\Command\CheckExpiredPermisCommand => ($container->privates['App\\Command\\CheckExpiredPermisCommand'] ?? $container->load('getCheckExpiredPermisCommandService')));
    }
}
