<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPermisTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PermisType' shared autowired service.
     *
     * @return \App\Form\PermisType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PermisType'] = new \App\Form\PermisType(($container->privates['App\\Repository\\QuizRepository'] ?? $container->load('getQuizRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
