<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.59sDmZo.App\Entity\Quiz' shared service.
     *
     * @return \App\Entity\Quiz
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.59sDmZo": it needs an instance of "App\\Entity\\Quiz" but this type has been excluded in "config/services.yaml".');
    }
}
