<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizApiClientService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\QuizApiClient' shared autowired service.
     *
     * @return \App\Service\QuizApiClient
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\QuizApiClient'] = new \App\Service\QuizApiClient(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));
    }
}
