<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\QuizController' shared autowired service.
     *
     * @return \App\Controller\QuizController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\QuizController'] = $instance = new \App\Controller\QuizController(($container->privates['App\\Service\\TwilioWhatsappService'] ??= new \App\Service\TwilioWhatsappService()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\QuizController', $container));

        return $instance;
    }
}
