<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationSearchTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ReservationSearchType' shared autowired service.
     *
     * @return \App\Form\ReservationSearchType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ReservationSearchType'] = new \App\Form\ReservationSearchType();
    }
}
