<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\RatingType' shared autowired service.
     *
     * @return \App\Form\RatingType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RatingType'] = new \App\Form\RatingType();
    }
}
