<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduler_MessengerTransportFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'scheduler.messenger_transport_factory' shared service.
     *
     * @return \Symfony\Component\Scheduler\Messenger\SchedulerTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['scheduler.messenger_transport_factory'] = new \Symfony\Component\Scheduler\Messenger\SchedulerTransportFactory(($container->privates['.service_locator.Xbsa8iG'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], [])), ($container->privates['clock'] ??= new \Symfony\Component\Clock\Clock()));
    }
}
