<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwilioWhatsappServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\TwilioWhatsappService' shared autowired service.
     *
     * @return \App\Service\TwilioWhatsappService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\TwilioWhatsappService'] = new \App\Service\TwilioWhatsappService();
    }
}
