<?php

namespace ContainerHa0n4Nm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehiculeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\VehiculeRepository' shared autowired service.
     *
     * @return \App\Repository\VehiculeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\VehiculeRepository'] = new \App\Repository\VehiculeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
