<?php

namespace ContainerRVQ4Xd5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NQQUOtxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NQQUOtx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NQQUOtx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'geminiService' => ['privates', 'App\\Service\\GeminiService', NULL, 'Cannot autowire service "App\\Service\\GeminiService": argument "$apiKey" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'geminiService' => 'App\\Service\\GeminiService',
        ]);
    }
}
