<?php

namespace ContainerRVQ4Xd5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmploye2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.je7oNoj.App\Entity\Employe' shared service.
     *
     * @return \App\Entity\Employe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.je7oNoj": it needs an instance of "App\\Entity\\Employe" but this type has been excluded in "config/services.yaml".');
    }
}
