<?php

namespace ContainerRVQ4Xd5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeminiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GeminiService' shared autowired service.
     *
     * @return \App\Service\GeminiService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\GeminiService": argument "$apiKey" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
