<?php

namespace ContainerSxnloWQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y2RT8vnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y2RT8vn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y2RT8vn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'permisRepository' => ['privates', 'App\\Repository\\PermisRepository', 'getPermisRepositoryService', true],
        ], [
            'permisRepository' => 'App\\Repository\\PermisRepository',
        ]);
    }
}
