<?php

namespace ContainerSxnloWQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9WLJ_XdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9WLJ.xd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9WLJ.xd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carteGrise' => ['privates', '.errored..service_locator.9WLJ.xd.App\\Entity\\CarteGrise', NULL, 'Cannot autowire service ".service_locator.9WLJ.xd": it needs an instance of "App\\Entity\\CarteGrise" but this type has been excluded in "config/services.yaml".'],
        ], [
            'carteGrise' => 'App\\Entity\\CarteGrise',
        ]);
    }
}
