<?php

namespace ContainerSxnloWQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwilioWhatsappServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TwilioWhatsappService' shared autowired service.
     *
     * @return \App\Service\TwilioWhatsappService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TwilioWhatsappService.php';

        return $container->privates['App\\Service\\TwilioWhatsappService'] = new \App\Service\TwilioWhatsappService();
    }
}
