<?php

namespace ContainerWG4PPCF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WZvLqvGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wZvLqvG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wZvLqvG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carteGriseRepo' => ['privates', 'App\\Repository\\CarteGriseRepository', 'getCarteGriseRepositoryService', true],
            'employeRepository' => ['privates', 'App\\Repository\\EmployeRepository', 'getEmployeRepositoryService', true],
            'equipementRepository' => ['privates', 'App\\Repository\\EquipementRepository', 'getEquipementRepositoryService', true],
            'reservationRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'vehiculeRepo' => ['privates', 'App\\Repository\\VehiculeRepository', 'getVehiculeRepositoryService', true],
        ], [
            'carteGriseRepo' => 'App\\Repository\\CarteGriseRepository',
            'employeRepository' => 'App\\Repository\\EmployeRepository',
            'equipementRepository' => 'App\\Repository\\EquipementRepository',
            'reservationRepo' => 'App\\Repository\\ReservationRepository',
            'vehiculeRepo' => 'App\\Repository\\VehiculeRepository',
        ]);
    }
}
