<?php

namespace ContainerWG4PPCF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContratService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4_v.oH0.App\Entity\Contrat' shared service.
     *
     * @return \App\Entity\Contrat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4_v.oH0": it needs an instance of "App\\Entity\\Contrat" but this type has been excluded in "config/services.yaml".');
    }
}
