<?php

namespace ContainerWG4PPCF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIaGuideServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\IaGuideService' shared autowired service.
     *
     * @return \App\Service\IaGuideService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'IaGuideService.php';

        $a = ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService'));

        if (isset($container->privates['App\\Service\\IaGuideService'])) {
            return $container->privates['App\\Service\\IaGuideService'];
        }

        return $container->privates['App\\Service\\IaGuideService'] = new \App\Service\IaGuideService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->services['knp_snappy.pdf'] ?? $container->load('getKnpSnappy_PdfService')), $a);
    }
}
