<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CarteGrise extends \App\Entity\CarteGrise implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresseProprietaire' => [parent::class, 'adresseProprietaire', null],
        "\0".parent::class."\0".'dateEmission' => [parent::class, 'dateEmission', null],
        "\0".parent::class."\0".'dateExpiration' => [parent::class, 'dateExpiration', null],
        "\0".parent::class."\0".'idCarteGrise' => [parent::class, 'idCarteGrise', null],
        "\0".parent::class."\0".'numeroCarteGrise' => [parent::class, 'numeroCarteGrise', null],
        "\0".parent::class."\0".'proprietaire' => [parent::class, 'proprietaire', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'vehicules' => [parent::class, 'vehicules', null],
        'adresseProprietaire' => [parent::class, 'adresseProprietaire', null],
        'dateEmission' => [parent::class, 'dateEmission', null],
        'dateExpiration' => [parent::class, 'dateExpiration', null],
        'idCarteGrise' => [parent::class, 'idCarteGrise', null],
        'numeroCarteGrise' => [parent::class, 'numeroCarteGrise', null],
        'proprietaire' => [parent::class, 'proprietaire', null],
        'user' => [parent::class, 'user', null],
        'vehicules' => [parent::class, 'vehicules', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
