<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehicule extends \App\Entity\Vehicule implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'carteGrise' => [parent::class, 'carteGrise', null],
        "\0".parent::class."\0".'couleur' => [parent::class, 'couleur', null],
        "\0".parent::class."\0".'idVehicule' => [parent::class, 'idVehicule', null],
        "\0".parent::class."\0".'immatriculation' => [parent::class, 'immatriculation', null],
        "\0".parent::class."\0".'kilometrage' => [parent::class, 'kilometrage', null],
        "\0".parent::class."\0".'marque' => [parent::class, 'marque', null],
        "\0".parent::class."\0".'modele' => [parent::class, 'modele', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'carteGrise' => [parent::class, 'carteGrise', null],
        'couleur' => [parent::class, 'couleur', null],
        'idVehicule' => [parent::class, 'idVehicule', null],
        'immatriculation' => [parent::class, 'immatriculation', null],
        'kilometrage' => [parent::class, 'kilometrage', null],
        'marque' => [parent::class, 'marque', null],
        'modele' => [parent::class, 'modele', null],
        'reservations' => [parent::class, 'reservations', null],
        'statut' => [parent::class, 'statut', null],
        'type' => [parent::class, 'type', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
