<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paiement extends \App\Entity\Paiement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cvc' => [parent::class, 'cvc', null, 16],
        "\0".parent::class."\0".'dateExpiration' => [parent::class, 'dateExpiration', null, 16],
        "\0".parent::class."\0".'datePaiement' => [parent::class, 'datePaiement', null, 16],
        "\0".parent::class."\0".'id_paiement' => [parent::class, 'id_paiement', null, 16],
        "\0".parent::class."\0".'nomTitulaireCarte' => [parent::class, 'nomTitulaireCarte', null, 16],
        "\0".parent::class."\0".'numeroCarte' => [parent::class, 'numeroCarte', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'reservation' => [parent::class, 'reservation', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        'cvc' => [parent::class, 'cvc', null, 16],
        'dateExpiration' => [parent::class, 'dateExpiration', null, 16],
        'datePaiement' => [parent::class, 'datePaiement', null, 16],
        'id_paiement' => [parent::class, 'id_paiement', null, 16],
        'nomTitulaireCarte' => [parent::class, 'nomTitulaireCarte', null, 16],
        'numeroCarte' => [parent::class, 'numeroCarte', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'reservation' => [parent::class, 'reservation', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
