<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \App\Entity\Reservation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateReservation' => [parent::class, 'dateReservation', null, 16],
        "\0".parent::class."\0".'factures' => [parent::class, 'factures', null, 16],
        "\0".parent::class."\0".'heureReservation' => [parent::class, 'heureReservation', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'paiements' => [parent::class, 'paiements', null, 16],
        "\0".parent::class."\0".'serviceId' => [parent::class, 'serviceId', null, 16],
        "\0".parent::class."\0".'userId' => [parent::class, 'userId', null, 16],
        "\0".parent::class."\0".'vehiculeId' => [parent::class, 'vehiculeId', null, 16],
        'dateReservation' => [parent::class, 'dateReservation', null, 16],
        'factures' => [parent::class, 'factures', null, 16],
        'heureReservation' => [parent::class, 'heureReservation', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'paiements' => [parent::class, 'paiements', null, 16],
        'serviceId' => [parent::class, 'serviceId', null, 16],
        'userId' => [parent::class, 'userId', null, 16],
        'vehiculeId' => [parent::class, 'vehiculeId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
