<?php

namespace ContainerNQgt8wx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JRCrJ6NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jRCrJ6N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jRCrJ6N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'permis' => ['privates', '.errored..service_locator.jRCrJ6N.App\\Entity\\Permis', NULL, 'Cannot autowire service ".service_locator.jRCrJ6N": it needs an instance of "App\\Entity\\Permis" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'permis' => 'App\\Entity\\Permis',
        ]);
    }
}
