controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

connect_google_start:
    path: /connect/google
    controller: App\Controller\ConnectController::connectGoogle

connect_google_check:
    path: /connect/google/check
    controller: App\Controller\ConnectController::connectGoogleCheck