parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\QuizApiClient:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%env(GEMINI_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\TwilioWhatsappService: ~
    
    App\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_subscriber }
