<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSpEI8xi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSpEI8xi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSpEI8xi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSpEI8xi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSpEI8xi\App_KernelDevDebugContainer([
    'container.build_hash' => 'SpEI8xi',
    'container.build_id' => '2c1ae01c',
    'container.build_time' => 1745661436,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSpEI8xi');
