<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNQgt8wx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNQgt8wx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNQgt8wx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNQgt8wx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNQgt8wx\App_KernelDevDebugContainer([
    'container.build_hash' => 'NQgt8wx',
    'container.build_id' => 'c8c1f980',
    'container.build_time' => 1745680642,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNQgt8wx');
