<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Quiz extends \App\Entity\Quiz implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateTest' => [parent::class, 'dateTest', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'idUser' => [parent::class, 'idUser', null],
        "\0".parent::class."\0".'permis' => [parent::class, 'permis', null],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null],
        "\0".parent::class."\0".'score' => [parent::class, 'score', null],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null],
        'dateTest' => [parent::class, 'dateTest', null],
        'id' => [parent::class, 'id', null],
        'idUser' => [parent::class, 'idUser', null],
        'permis' => [parent::class, 'permis', null],
        'rating' => [parent::class, 'rating', null],
        'score' => [parent::class, 'score', null],
        'statut' => [parent::class, 'statut', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
