<?php

namespace ContainerWssgg6j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckExpiredPermisCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CheckExpiredPermisCommand' shared autowired service.
     *
     * @return \App\Command\CheckExpiredPermisCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CheckExpiredPermisCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TwilioWhatsappService.php';

        $container->privates['App\\Command\\CheckExpiredPermisCommand'] = $instance = new \App\Command\CheckExpiredPermisCommand(($container->privates['App\\Repository\\PermisRepository'] ?? $container->load('getPermisRepositoryService')), ($container->privates['App\\Service\\TwilioWhatsappService'] ??= new \App\Service\TwilioWhatsappService()));

        $instance->setName('app:check-expired-permis');
        $instance->setDescription('Checks for expired permits and sends WhatsApp notifications');

        return $instance;
    }
}
