<?php

namespace ContainerU8tscJF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M0B_ZWsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M0B.zWs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M0B.zWs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vehicule' => ['privates', '.errored..service_locator.M0B.zWs.App\\Entity\\Vehicule', NULL, 'Cannot autowire service ".service_locator.M0B.zWs": it needs an instance of "App\\Entity\\Vehicule" but this type has been excluded in "config/services.yaml".'],
        ], [
            'vehicule' => 'App\\Entity\\Vehicule',
        ]);
    }
}
