<?php

namespace ContainerU8tscJF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AcbPQp5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.acbPQp5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.acbPQp5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carteGriseRepo' => ['privates', 'App\\Repository\\CarteGriseRepository', 'getCarteGriseRepositoryService', true],
            'vehiculeRepo' => ['privates', 'App\\Repository\\VehiculeRepository', 'getVehiculeRepositoryService', true],
        ], [
            'carteGriseRepo' => 'App\\Repository\\CarteGriseRepository',
            'vehiculeRepo' => 'App\\Repository\\VehiculeRepository',
        ]);
    }
}
