<?php

namespace ContainerU8tscJF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZT40IkPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zT40IkP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zT40IkP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'vehicule' => ['privates', '.errored..service_locator.zT40IkP.App\\Entity\\Vehicule', NULL, 'Cannot autowire service ".service_locator.zT40IkP": it needs an instance of "App\\Entity\\Vehicule" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'vehicule' => 'App\\Entity\\Vehicule',
        ]);
    }
}
