<?php

namespace ContainerU8tscJF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wko0FFzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wko0FFz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wko0FFz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientRegistry' => ['privates', '.errored.iL0PUj3', NULL, 'Cannot determine controller argument for "App\\Controller\\GoogleController::connectAction()": the $clientRegistry argument is type-hinted with the non-existent class or interface: "KnpU\\OAuth2ClientBundle\\Client\\ClientRegistry".'],
        ], [
            'clientRegistry' => '?',
        ]);
    }
}
