<?php

namespace ContainerU8tscJF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WYMas87Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wYMas87' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wYMas87'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'equipement' => ['privates', '.errored..service_locator.wYMas87.App\\Entity\\Equipement', NULL, 'Cannot autowire service ".service_locator.wYMas87": it needs an instance of "App\\Entity\\Equipement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'equipement' => 'App\\Entity\\Equipement',
        ]);
    }
}
