<?php

namespace ContainerU8tscJF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehicule2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zT40IkP.App\Entity\Vehicule' shared service.
     *
     * @return \App\Entity\Vehicule
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zT40IkP": it needs an instance of "App\\Entity\\Vehicule" but this type has been excluded in "config/services.yaml".');
    }
}
