<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Employe__CLASSMETADATA__' => 0,
'App__Entity__Equipement__CLASSMETADATA__' => 1,
'App__Entity__User__CLASSMETADATA__' => 2,
'App__Entity__Carte_grise__CLASSMETADATA__' => 3,
'App__Entity__Compte__CLASSMETADATA__' => 4,
'App__Entity__Paiement__CLASSMETADATA__' => 5,
'App__Entity__Permis__CLASSMETADATA__' => 6,
'App__Entity__Quiz__CLASSMETADATA__' => 7,
'App__Entity__Rapport__CLASSMETADATA__' => 8,
'App__Entity__Reservation__CLASSMETADATA__' => 9,
'App__Entity__Resultat__CLASSMETADATA__' => 10,
'App__Entity__Service__CLASSMETADATA__' => 11,
'App__Entity__Vehicule__CLASSMETADATA__' => 12,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Employe',
                ],
                'identifier' => [
                    [
                        'idEmploye',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'idEmploye' => $o[1],
                        'nom' => $o[2],
                        'prenom' => $o[3],
                        'email' => $o[4],
                        'age' => $o[5],
                        'dateEmbauche' => $o[6],
                        'poste' => $o[7],
                        'tel' => $o[8],
                        'salaire' => $o[9],
                        'statut' => $o[10],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_employe' => 'idEmploye',
                        'nom' => 'nom',
                        'prenom' => 'prenom',
                        'email' => 'email',
                        'age' => 'age',
                        'date_embauche' => 'dateEmbauche',
                        'poste' => 'poste',
                        'tel' => 'tel',
                        'salaire' => 'salaire',
                        'statut' => 'statut',
                    ],
                ],
                'columnNames' => [
                    [
                        'idEmploye' => 'id_employe',
                        'nom' => 'nom',
                        'prenom' => 'prenom',
                        'email' => 'email',
                        'age' => 'age',
                        'dateEmbauche' => 'date_embauche',
                        'poste' => 'poste',
                        'tel' => 'tel',
                        'salaire' => 'salaire',
                        'statut' => 'statut',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'employe',
                    ],
                ],
                'associationMappings' => [
                    [
                        'id_service' => $o[11],
                        'equipements' => $o[13],
                        'permiss' => $o[14],
                    ],
                ],
                'idGenerator' => [
                    $o[15],
                ],
                'name' => [
                    'App\\Entity\\Employe',
                    12 => 'id_service',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'integer',
                    'date',
                    'string',
                    'string',
                    'float',
                    'string',
                ],
                'fieldName' => [
                    1 => 'idEmploye',
                    'nom',
                    'prenom',
                    'email',
                    'age',
                    'dateEmbauche',
                    'poste',
                    'tel',
                    'salaire',
                    'statut',
                ],
                'columnName' => [
                    1 => 'id_employe',
                    'nom',
                    'prenom',
                    'email',
                    'age',
                    'date_embauche',
                    'poste',
                    'tel',
                    'salaire',
                    'statut',
                ],
                'length' => [
                    2 => 50,
                    50,
                    100,
                    7 => 50,
                    20,
                    10 => 20,
                ],
                'fetch' => [
                    11 => 2,
                    13 => 2,
                    2,
                ],
                'sourceEntity' => [
                    11 => 'App\\Entity\\Employe',
                    13 => 'App\\Entity\\Employe',
                    'App\\Entity\\Employe',
                ],
                'inversedBy' => [
                    11 => 'employes',
                ],
                'sourceToTargetKeyColumns' => [
                    11 => [
                        'id_service' => 'id_service',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    11 => [
                        'id_service' => 'id_service',
                    ],
                ],
                'joinColumns' => [
                    11 => [
                        $o[12],
                    ],
                ],
                'joinColumnFieldNames' => [
                    11 => [
                        'id_service' => 'id_service',
                    ],
                ],
                'unique' => [
                    12 => false,
                ],
                'onDelete' => [
                    12 => 'CASCADE',
                ],
                'nullable' => [
                    12 => true,
                ],
                'referencedColumnName' => [
                    12 => 'id_service',
                ],
                'mappedBy' => [
                    13 => 'id_employe',
                    'idEmploye',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    11 => 'id_service',
                    13 => 'equipements',
                    'permiss',
                ],
                'targetEntity' => [
                    11 => 'App\\Entity\\Service',
                    13 => 'App\\Entity\\Equipement',
                    'App\\Entity\\Permis',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Equipement',
                ],
                'identifier' => [
                    [
                        'idEquipement',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'idEquipement' => $o[1],
                        'nom' => $o[2],
                        'description' => $o[3],
                        'categorie' => $o[4],
                        'etat' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_equipement' => 'idEquipement',
                        'nom' => 'nom',
                        'description' => 'description',
                        'categorie' => 'categorie',
                        'etat' => 'etat',
                    ],
                ],
                'columnNames' => [
                    [
                        'idEquipement' => 'id_equipement',
                        'nom' => 'nom',
                        'description' => 'description',
                        'categorie' => 'categorie',
                        'etat' => 'etat',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'equipement',
                    ],
                ],
                'idGenerator' => [
                    $o[6],
                ],
                'name' => [
                    'App\\Entity\\Equipement',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'text',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'idEquipement',
                    'nom',
                    'description',
                    'categorie',
                    'etat',
                ],
                'columnName' => [
                    1 => 'id_equipement',
                    'nom',
                    'description',
                    'categorie',
                    'etat',
                ],
                'length' => [
                    2 => 100,
                    4 => 50,
                    20,
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'nom' => $o[2],
                        'prenom' => $o[3],
                        'tel' => $o[4],
                        'localisation' => $o[5],
                        'email' => $o[6],
                        'mot_de_passe' => $o[7],
                        'status' => $o[8],
                        'role' => $o[9],
                        'image' => $o[10],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'prenom' => 'prenom',
                        'tel' => 'tel',
                        'localisation' => 'localisation',
                        'email' => 'email',
                        'mot_de_passe' => 'mot_de_passe',
                        'status' => 'status',
                        'role' => 'role',
                        'image' => 'image',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'prenom' => 'prenom',
                        'tel' => 'tel',
                        'localisation' => 'localisation',
                        'email' => 'email',
                        'mot_de_passe' => 'mot_de_passe',
                        'status' => 'status',
                        'role' => 'role',
                        'image' => 'image',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                    ],
                ],
                'associationMappings' => [
                    [
                        'comptes' => $o[11],
                        'reservations' => $o[12],
                    ],
                ],
                'idGenerator' => [
                    $o[13],
                ],
                'name' => [
                    'App\\Entity\\User',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'nom',
                    'prenom',
                    'tel',
                    'localisation',
                    'email',
                    'mot_de_passe',
                    'status',
                    'role',
                    'image',
                ],
                'columnName' => [
                    1 => 'id',
                    'nom',
                    'prenom',
                    'tel',
                    'localisation',
                    'email',
                    'mot_de_passe',
                    'status',
                    'role',
                    'image',
                ],
                'length' => [
                    2 => 50,
                    50,
                    20,
                    100,
                    150,
                    150,
                    50,
                    50,
                    255,
                ],
                'nullable' => [
                    10 => true,
                ],
                'fetch' => [
                    11 => 2,
                    2,
                ],
                'sourceEntity' => [
                    11 => 'App\\Entity\\User',
                    'App\\Entity\\User',
                ],
                'mappedBy' => [
                    11 => 'id_user',
                    'user_id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    11 => 'comptes',
                    'reservations',
                ],
                'targetEntity' => [
                    11 => 'App\\Entity\\Compte',
                    'App\\Entity\\Reservation',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Carte_grise',
                ],
                'identifier' => [
                    [
                        'id_carte_grise',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id_carte_grise' => $o[1],
                        'numero_carte_grise' => $o[2],
                        'proprietaire' => $o[3],
                        'adresse_proprietaire' => $o[4],
                        'date_emission' => $o[5],
                        'date_expiration' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_carte_grise' => 'id_carte_grise',
                        'numero_carte_grise' => 'numero_carte_grise',
                        'proprietaire' => 'proprietaire',
                        'adresse_proprietaire' => 'adresse_proprietaire',
                        'date_emission' => 'date_emission',
                        'date_expiration' => 'date_expiration',
                    ],
                ],
                'columnNames' => [
                    [
                        'id_carte_grise' => 'id_carte_grise',
                        'numero_carte_grise' => 'numero_carte_grise',
                        'proprietaire' => 'proprietaire',
                        'adresse_proprietaire' => 'adresse_proprietaire',
                        'date_emission' => 'date_emission',
                        'date_expiration' => 'date_expiration',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'carte_grise',
                    ],
                ],
                'associationMappings' => [
                    [
                        'id_user' => $o[7],
                        'vehicules' => $o[9],
                    ],
                ],
                'idGenerator' => [
                    $o[10],
                ],
                'name' => [
                    'App\\Entity\\Carte_grise',
                    8 => 'id_user',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'date',
                    'date',
                ],
                'fieldName' => [
                    1 => 'id_carte_grise',
                    'numero_carte_grise',
                    'proprietaire',
                    'adresse_proprietaire',
                    'date_emission',
                    'date_expiration',
                ],
                'columnName' => [
                    1 => 'id_carte_grise',
                    'numero_carte_grise',
                    'proprietaire',
                    'adresse_proprietaire',
                    'date_emission',
                    'date_expiration',
                ],
                'length' => [
                    2 => 50,
                    100,
                    255,
                ],
                'fetch' => [
                    7 => 2,
                    9 => 2,
                ],
                'sourceEntity' => [
                    7 => 'App\\Entity\\Carte_grise',
                    9 => 'App\\Entity\\Carte_grise',
                ],
                'inversedBy' => [
                    7 => 'carte_grises',
                ],
                'sourceToTargetKeyColumns' => [
                    7 => [
                        'id_user' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    7 => [
                        'id' => 'id_user',
                    ],
                ],
                'joinColumns' => [
                    7 => [
                        $o[8],
                    ],
                ],
                'joinColumnFieldNames' => [
                    7 => [
                        'id_user' => 'id_user',
                    ],
                ],
                'unique' => [
                    8 => false,
                ],
                'onDelete' => [
                    8 => 'CASCADE',
                ],
                'nullable' => [
                    8 => true,
                ],
                'referencedColumnName' => [
                    8 => 'id',
                ],
                'mappedBy' => [
                    9 => 'id_carte_grise',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    7 => 'id_user',
                    9 => 'vehicules',
                ],
                'targetEntity' => [
                    7 => 'App\\Entity\\User',
                    9 => 'App\\Entity\\Vehicule',
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Compte',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'mot_de_passe' => $o[2],
                        'image' => $o[3],
                        'email' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'mot_de_passe' => 'mot_de_passe',
                        'image' => 'image',
                        'email' => 'email',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'mot_de_passe' => 'mot_de_passe',
                        'image' => 'image',
                        'email' => 'email',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'compte',
                    ],
                ],
                'associationMappings' => [
                    [
                        'id_user' => $o[5],
                    ],
                ],
                'idGenerator' => [
                    $o[7],
                ],
                'name' => [
                    'App\\Entity\\Compte',
                    6 => 'id_user',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'mot_de_passe',
                    'image',
                    'email',
                ],
                'columnName' => [
                    1 => 'id',
                    'mot_de_passe',
                    'image',
                    'email',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                ],
                'fetch' => [
                    5 => 2,
                ],
                'sourceEntity' => [
                    5 => 'App\\Entity\\Compte',
                ],
                'inversedBy' => [
                    5 => 'comptes',
                ],
                'sourceToTargetKeyColumns' => [
                    5 => [
                        'id_user' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    5 => [
                        'id' => 'id_user',
                    ],
                ],
                'joinColumns' => [
                    5 => [
                        $o[6],
                    ],
                ],
                'joinColumnFieldNames' => [
                    5 => [
                        'id_user' => 'id_user',
                    ],
                ],
                'unique' => [
                    6 => false,
                ],
                'onDelete' => [
                    6 => 'CASCADE',
                ],
                'nullable' => [
                    6 => true,
                ],
                'referencedColumnName' => [
                    6 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    5 => 'id_user',
                ],
                'targetEntity' => [
                    5 => 'App\\Entity\\User',
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Paiement',
                ],
                'identifier' => [
                    [
                        'id_paiement',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id_paiement' => $o[1],
                        'numeroCarte' => $o[2],
                        'date_paiement' => $o[3],
                        'prix' => $o[4],
                        'statut' => $o[5],
                        'telephone' => $o[6],
                        'date_expiration' => $o[7],
                        'cvc' => $o[8],
                        'nom_titulaire_carte' => $o[9],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_paiement' => 'id_paiement',
                        'numero_carte' => 'numeroCarte',
                        'date_paiement' => 'date_paiement',
                        'prix' => 'prix',
                        'statut' => 'statut',
                        'telephone' => 'telephone',
                        'date_expiration' => 'date_expiration',
                        'cvc' => 'cvc',
                        'nom_titulaire_carte' => 'nom_titulaire_carte',
                    ],
                ],
                'columnNames' => [
                    [
                        'id_paiement' => 'id_paiement',
                        'numeroCarte' => 'numero_carte',
                        'date_paiement' => 'date_paiement',
                        'prix' => 'prix',
                        'statut' => 'statut',
                        'telephone' => 'telephone',
                        'date_expiration' => 'date_expiration',
                        'cvc' => 'cvc',
                        'nom_titulaire_carte' => 'nom_titulaire_carte',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'paiement',
                    ],
                ],
                'associationMappings' => [
                    [
                        'id_reservation' => $o[10],
                        'resultats' => $o[12],
                    ],
                ],
                'idGenerator' => [
                    $o[13],
                ],
                'name' => [
                    'App\\Entity\\Paiement',
                    11 => 'id_reservation',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'datetime',
                    'float',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id_paiement',
                    'numeroCarte',
                    'date_paiement',
                    'prix',
                    'statut',
                    'telephone',
                    'date_expiration',
                    'cvc',
                    'nom_titulaire_carte',
                ],
                'columnName' => [
                    1 => 'id_paiement',
                    'numero_carte',
                    'date_paiement',
                    'prix',
                    'statut',
                    'telephone',
                    'date_expiration',
                    'cvc',
                    'nom_titulaire_carte',
                ],
                'length' => [
                    2 => 255,
                    5 => 20,
                    20,
                    10,
                    5,
                    100,
                ],
                'fetch' => [
                    10 => 2,
                    12 => 2,
                ],
                'sourceEntity' => [
                    10 => 'App\\Entity\\Paiement',
                    12 => 'App\\Entity\\Paiement',
                ],
                'inversedBy' => [
                    10 => 'paiements',
                ],
                'sourceToTargetKeyColumns' => [
                    10 => [
                        'id_reservation' => 'id_reservation',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    10 => [
                        'id_reservation' => 'id_reservation',
                    ],
                ],
                'joinColumns' => [
                    10 => [
                        $o[11],
                    ],
                ],
                'joinColumnFieldNames' => [
                    10 => [
                        'id_reservation' => 'id_reservation',
                    ],
                ],
                'unique' => [
                    11 => false,
                ],
                'onDelete' => [
                    11 => 'CASCADE',
                ],
                'nullable' => [
                    11 => true,
                ],
                'referencedColumnName' => [
                    11 => 'id_reservation',
                ],
                'mappedBy' => [
                    12 => 'id_paiement',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    10 => 'id_reservation',
                    12 => 'resultats',
                ],
                'targetEntity' => [
                    10 => 'App\\Entity\\Reservation',
                    12 => 'App\\Entity\\Resultat',
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Permis',
                ],
                'identifier' => [
                    [
                        'id_permis',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id_permis' => $o[1],
                        'numero_permis' => $o[2],
                        'categorie' => $o[3],
                        'date_delivrance' => $o[4],
                        'date_expiration' => $o[5],
                        'etat' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_permis' => 'id_permis',
                        'numero_permis' => 'numero_permis',
                        'categorie' => 'categorie',
                        'date_delivrance' => 'date_delivrance',
                        'date_expiration' => 'date_expiration',
                        'etat' => 'etat',
                    ],
                ],
                'columnNames' => [
                    [
                        'id_permis' => 'id_permis',
                        'numero_permis' => 'numero_permis',
                        'categorie' => 'categorie',
                        'date_delivrance' => 'date_delivrance',
                        'date_expiration' => 'date_expiration',
                        'etat' => 'etat',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'permis',
                    ],
                ],
                'associationMappings' => [
                    [
                        'id_employe' => $o[7],
                        'quizs' => $o[9],
                    ],
                ],
                'idGenerator' => [
                    $o[10],
                ],
                'name' => [
                    'App\\Entity\\Permis',
                    8 => 'id_employe',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'date',
                    'date',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id_permis',
                    'numero_permis',
                    'categorie',
                    'date_delivrance',
                    'date_expiration',
                    'etat',
                ],
                'columnName' => [
                    1 => 'id_permis',
                    'numero_permis',
                    'categorie',
                    'date_delivrance',
                    'date_expiration',
                    'etat',
                ],
                'length' => [
                    2 => 50,
                    20,
                    6 => 20,
                ],
                'fetch' => [
                    7 => 2,
                    9 => 2,
                ],
                'sourceEntity' => [
                    7 => 'App\\Entity\\Permis',
                    9 => 'App\\Entity\\Permis',
                ],
                'inversedBy' => [
                    7 => 'permiss',
                ],
                'sourceToTargetKeyColumns' => [
                    7 => [
                        'id_employe' => 'id_employe',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    7 => [
                        'id_employe' => 'id_employe',
                    ],
                ],
                'joinColumns' => [
                    7 => [
                        $o[8],
                    ],
                ],
                'joinColumnFieldNames' => [
                    7 => [
                        'id_employe' => 'id_employe',
                    ],
                ],
                'unique' => [
                    8 => false,
                ],
                'onDelete' => [
                    8 => 'CASCADE',
                ],
                'nullable' => [
                    8 => true,
                ],
                'referencedColumnName' => [
                    8 => 'id_employe',
                ],
                'mappedBy' => [
                    9 => 'id_permis',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    7 => 'id_employe',
                    9 => 'quizs',
                ],
                'targetEntity' => [
                    7 => 'App\\Entity\\Employe',
                    9 => 'App\\Entity\\Quiz',
                ],
            ],
        ],
        $o[0],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Quiz',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'score' => $o[2],
                        'statut' => $o[3],
                        'date_test' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'score' => 'score',
                        'statut' => 'statut',
                        'date_test' => 'date_test',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'score' => 'score',
                        'statut' => 'statut',
                        'date_test' => 'date_test',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'quiz',
                    ],
                ],
                'associationMappings' => [
                    [
                        'id_permis' => $o[5],
                    ],
                ],
                'idGenerator' => [
                    $o[7],
                ],
                'name' => [
                    'App\\Entity\\Quiz',
                    6 => 'id_permis',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'integer',
                    'string',
                    'date',
                ],
                'fieldName' => [
                    1 => 'id',
                    'score',
                    'statut',
                    'date_test',
                ],
                'columnName' => [
                    1 => 'id',
                    'score',
                    'statut',
                    'date_test',
                ],
                'length' => [
                    3 => 20,
                ],
                'fetch' => [
                    5 => 2,
                ],
                'sourceEntity' => [
                    5 => 'App\\Entity\\Quiz',
                ],
                'inversedBy' => [
                    5 => 'quizs',
                ],
                'sourceToTargetKeyColumns' => [
                    5 => [
                        'id_permis' => 'id_permis',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    5 => [
                        'id_permis' => 'id_permis',
                    ],
                ],
                'joinColumns' => [
                    5 => [
                        $o[6],
                    ],
                ],
                'joinColumnFieldNames' => [
                    5 => [
                        'id_permis' => 'id_permis',
                    ],
                ],
                'unique' => [
                    6 => false,
                ],
                'onDelete' => [
                    6 => 'CASCADE',
                ],
                'nullable' => [
                    6 => true,
                ],
                'referencedColumnName' => [
                    6 => 'id_permis',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    5 => 'id_permis',
                ],
                'targetEntity' => [
                    5 => 'App\\Entity\\Permis',
                ],
            ],
        ],
        $o[0],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Rapport',
                ],
                'identifier' => [
                    [
                        'id_rapport',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id_rapport' => $o[1],
                        'direction' => $o[2],
                        'visibilite' => $o[3],
                        'huileDefault' => $o[4],
                        'pneaumatique' => $o[5],
                        'echappement' => $o[6],
                        'carrosorie' => $o[7],
                        'eclairage' => $o[8],
                        'freinage' => $o[9],
                        'date' => $o[10],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_rapport' => 'id_rapport',
                        'direction' => 'direction',
                        'visibilite' => 'visibilite',
                        'huile_default' => 'huileDefault',
                        'pneaumatique' => 'pneaumatique',
                        'echappement' => 'echappement',
                        'carrosorie' => 'carrosorie',
                        'eclairage' => 'eclairage',
                        'freinage' => 'freinage',
                        'date' => 'date',
                    ],
                ],
                'columnNames' => [
                    [
                        'id_rapport' => 'id_rapport',
                        'direction' => 'direction',
                        'visibilite' => 'visibilite',
                        'huileDefault' => 'huile_default',
                        'pneaumatique' => 'pneaumatique',
                        'echappement' => 'echappement',
                        'carrosorie' => 'carrosorie',
                        'eclairage' => 'eclairage',
                        'freinage' => 'freinage',
                        'date' => 'date',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'rapport',
                    ],
                ],
                'associationMappings' => [
                    [
                        'id_resultat' => $o[11],
                    ],
                ],
                'idGenerator' => [
                    $o[13],
                ],
                'name' => [
                    'App\\Entity\\Rapport',
                    12 => 'id_resultat',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'date',
                ],
                'fieldName' => [
                    1 => 'id_rapport',
                    'direction',
                    'visibilite',
                    'huileDefault',
                    'pneaumatique',
                    'echappement',
                    'carrosorie',
                    'eclairage',
                    'freinage',
                    'date',
                ],
                'columnName' => [
                    1 => 'id_rapport',
                    'direction',
                    'visibilite',
                    'huile_default',
                    'pneaumatique',
                    'echappement',
                    'carrosorie',
                    'eclairage',
                    'freinage',
                    'date',
                ],
                'length' => [
                    2 => 150,
                    150,
                    150,
                    150,
                    150,
                    150,
                    150,
                    150,
                ],
                'fetch' => [
                    11 => 2,
                ],
                'sourceEntity' => [
                    11 => 'App\\Entity\\Rapport',
                ],
                'inversedBy' => [
                    11 => 'rapports',
                ],
                'sourceToTargetKeyColumns' => [
                    11 => [
                        'id_resultat' => 'id_resultat',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    11 => [
                        'id_resultat' => 'id_resultat',
                    ],
                ],
                'joinColumns' => [
                    11 => [
                        $o[12],
                    ],
                ],
                'joinColumnFieldNames' => [
                    11 => [
                        'id_resultat' => 'id_resultat',
                    ],
                ],
                'unique' => [
                    12 => false,
                ],
                'onDelete' => [
                    12 => 'CASCADE',
                ],
                'nullable' => [
                    12 => true,
                ],
                'referencedColumnName' => [
                    12 => 'id_resultat',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    11 => 'id_resultat',
                ],
                'targetEntity' => [
                    11 => 'App\\Entity\\Resultat',
                ],
            ],
        ],
        $o[0],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Reservation',
                ],
                'identifier' => [
                    [
                        'id_reservation',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id_reservation' => $o[1],
                        'date_reservation' => $o[2],
                        'heureReservation' => $o[3],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_reservation' => 'id_reservation',
                        'date_reservation' => 'date_reservation',
                        'heure_reservation' => 'heureReservation',
                    ],
                ],
                'columnNames' => [
                    [
                        'id_reservation' => 'id_reservation',
                        'date_reservation' => 'date_reservation',
                        'heureReservation' => 'heure_reservation',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'reservation',
                    ],
                ],
                'associationMappings' => [
                    [
                        'user_id' => $o[4],
                        'service_id' => $o[6],
                        'idVehicule' => $o[8],
                        'paiements' => $o[10],
                    ],
                ],
                'idGenerator' => [
                    $o[11],
                ],
                'name' => [
                    'App\\Entity\\Reservation',
                    5 => 'user_id',
                    7 => 'service_id',
                    9 => 'idVehicule',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'date',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id_reservation',
                    'date_reservation',
                    'heureReservation',
                ],
                'columnName' => [
                    1 => 'id_reservation',
                    'date_reservation',
                    'heure_reservation',
                ],
                'length' => [
                    3 => 255,
                ],
                'fetch' => [
                    4 => 2,
                    6 => 2,
                    8 => 2,
                    10 => 2,
                ],
                'sourceEntity' => [
                    4 => 'App\\Entity\\Reservation',
                    6 => 'App\\Entity\\Reservation',
                    8 => 'App\\Entity\\Reservation',
                    10 => 'App\\Entity\\Reservation',
                ],
                'inversedBy' => [
                    4 => 'reservations',
                    6 => 'reservations',
                    8 => 'reservations',
                ],
                'sourceToTargetKeyColumns' => [
                    4 => [
                        'user_id' => 'id',
                    ],
                    6 => [
                        'service_id' => 'id_service',
                    ],
                    8 => [
                        'idVehicule' => 'id_vehicule',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    4 => [
                        'id' => 'user_id',
                    ],
                    6 => [
                        'id_service' => 'service_id',
                    ],
                    8 => [
                        'id_vehicule' => 'idVehicule',
                    ],
                ],
                'joinColumns' => [
                    4 => [
                        $o[5],
                    ],
                    6 => [
                        $o[7],
                    ],
                    8 => [
                        $o[9],
                    ],
                ],
                'joinColumnFieldNames' => [
                    4 => [
                        'user_id' => 'user_id',
                    ],
                    6 => [
                        'service_id' => 'service_id',
                    ],
                    8 => [
                        'idVehicule' => 'idVehicule',
                    ],
                ],
                'unique' => [
                    5 => false,
                    7 => false,
                    9 => false,
                ],
                'onDelete' => [
                    5 => 'CASCADE',
                    7 => 'CASCADE',
                    9 => 'CASCADE',
                ],
                'nullable' => [
                    5 => true,
                    7 => true,
                    9 => true,
                ],
                'referencedColumnName' => [
                    5 => 'id',
                    7 => 'id_service',
                    9 => 'id_vehicule',
                ],
                'mappedBy' => [
                    10 => 'id_reservation',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    4 => 'user_id',
                    6 => 'service_id',
                    8 => 'idVehicule',
                    10 => 'paiements',
                ],
                'targetEntity' => [
                    4 => 'App\\Entity\\User',
                    6 => 'App\\Entity\\Service',
                    8 => 'App\\Entity\\Vehicule',
                    10 => 'App\\Entity\\Paiement',
                ],
            ],
        ],
        $o[0],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Resultat',
                ],
                'identifier' => [
                    [
                        'id_resultat',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id_resultat' => $o[1],
                        'direction' => $o[2],
                        'visibilite' => $o[3],
                        'huileDefault' => $o[4],
                        'pneaumatique' => $o[5],
                        'echappement' => $o[6],
                        'carrosorie' => $o[7],
                        'eclairage' => $o[8],
                        'freinage' => $o[9],
                        'vinSaisie' => $o[10],
                        'status' => $o[11],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_resultat' => 'id_resultat',
                        'direction' => 'direction',
                        'visibilite' => 'visibilite',
                        'huile_default' => 'huileDefault',
                        'pneaumatique' => 'pneaumatique',
                        'echappement' => 'echappement',
                        'carrosorie' => 'carrosorie',
                        'eclairage' => 'eclairage',
                        'freinage' => 'freinage',
                        'vin_saisie' => 'vinSaisie',
                        'status' => 'status',
                    ],
                ],
                'columnNames' => [
                    [
                        'id_resultat' => 'id_resultat',
                        'direction' => 'direction',
                        'visibilite' => 'visibilite',
                        'huileDefault' => 'huile_default',
                        'pneaumatique' => 'pneaumatique',
                        'echappement' => 'echappement',
                        'carrosorie' => 'carrosorie',
                        'eclairage' => 'eclairage',
                        'freinage' => 'freinage',
                        'vinSaisie' => 'vin_saisie',
                        'status' => 'status',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'resultat',
                    ],
                ],
                'associationMappings' => [
                    [
                        'id_service' => $o[12],
                        'id_paiement' => $o[14],
                        'rapports' => $o[16],
                    ],
                ],
                'idGenerator' => [
                    $o[17],
                ],
                'name' => [
                    'App\\Entity\\Resultat',
                    13 => 'id_service',
                    15 => 'id_paiement',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'boolean',
                    'boolean',
                    'boolean',
                    'boolean',
                    'boolean',
                    'boolean',
                    'boolean',
                    'boolean',
                    'string',
                    'boolean',
                ],
                'fieldName' => [
                    1 => 'id_resultat',
                    'direction',
                    'visibilite',
                    'huileDefault',
                    'pneaumatique',
                    'echappement',
                    'carrosorie',
                    'eclairage',
                    'freinage',
                    'vinSaisie',
                    'status',
                ],
                'columnName' => [
                    1 => 'id_resultat',
                    'direction',
                    'visibilite',
                    'huile_default',
                    'pneaumatique',
                    'echappement',
                    'carrosorie',
                    'eclairage',
                    'freinage',
                    'vin_saisie',
                    'status',
                ],
                'length' => [
                    10 => 255,
                ],
                'fetch' => [
                    12 => 2,
                    14 => 2,
                    16 => 2,
                ],
                'sourceEntity' => [
                    12 => 'App\\Entity\\Resultat',
                    14 => 'App\\Entity\\Resultat',
                    16 => 'App\\Entity\\Resultat',
                ],
                'inversedBy' => [
                    12 => 'resultats',
                    14 => 'resultats',
                ],
                'sourceToTargetKeyColumns' => [
                    12 => [
                        'id_service' => 'id_service',
                    ],
                    14 => [
                        'id_paiement' => 'id_paiement',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    12 => [
                        'id_service' => 'id_service',
                    ],
                    14 => [
                        'id_paiement' => 'id_paiement',
                    ],
                ],
                'joinColumns' => [
                    12 => [
                        $o[13],
                    ],
                    14 => [
                        $o[15],
                    ],
                ],
                'joinColumnFieldNames' => [
                    12 => [
                        'id_service' => 'id_service',
                    ],
                    14 => [
                        'id_paiement' => 'id_paiement',
                    ],
                ],
                'unique' => [
                    13 => false,
                    15 => false,
                ],
                'onDelete' => [
                    13 => 'CASCADE',
                    15 => 'CASCADE',
                ],
                'nullable' => [
                    13 => true,
                    15 => true,
                ],
                'referencedColumnName' => [
                    13 => 'id_service',
                    15 => 'id_paiement',
                ],
                'mappedBy' => [
                    16 => 'id_resultat',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    12 => 'id_service',
                    14 => 'id_paiement',
                    16 => 'rapports',
                ],
                'targetEntity' => [
                    12 => 'App\\Entity\\Service',
                    14 => 'App\\Entity\\Paiement',
                    16 => 'App\\Entity\\Rapport',
                ],
            ],
        ],
        $o[0],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Service',
                ],
                'identifier' => [
                    [
                        'id_service',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id_service' => $o[1],
                        'nom' => $o[2],
                        'type' => $o[3],
                        'heure_ouverture' => $o[4],
                        'heure_fermeture' => $o[5],
                        'prix' => $o[6],
                        'gouvernerat' => $o[7],
                        'numero' => $o[8],
                        'description' => $o[9],
                        'email' => $o[10],
                        'latitude' => $o[11],
                        'longitude' => $o[12],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_service' => 'id_service',
                        'nom' => 'nom',
                        'type' => 'type',
                        'heure_ouverture' => 'heure_ouverture',
                        'heure_fermeture' => 'heure_fermeture',
                        'prix' => 'prix',
                        'gouvernerat' => 'gouvernerat',
                        'numero' => 'numero',
                        'description' => 'description',
                        'email' => 'email',
                        'latitude' => 'latitude',
                        'longitude' => 'longitude',
                    ],
                ],
                'columnNames' => [
                    [
                        'id_service' => 'id_service',
                        'nom' => 'nom',
                        'type' => 'type',
                        'heure_ouverture' => 'heure_ouverture',
                        'heure_fermeture' => 'heure_fermeture',
                        'prix' => 'prix',
                        'gouvernerat' => 'gouvernerat',
                        'numero' => 'numero',
                        'description' => 'description',
                        'email' => 'email',
                        'latitude' => 'latitude',
                        'longitude' => 'longitude',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'service',
                    ],
                ],
                'associationMappings' => [
                    [
                        'employes' => $o[13],
                        'resultats' => $o[14],
                        'reservations' => $o[15],
                    ],
                ],
                'idGenerator' => [
                    $o[16],
                ],
                'name' => [
                    'App\\Entity\\Service',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'float',
                    'string',
                    'integer',
                    'string',
                    'string',
                    'float',
                    'float',
                ],
                'fieldName' => [
                    1 => 'id_service',
                    'nom',
                    'type',
                    'heure_ouverture',
                    'heure_fermeture',
                    'prix',
                    'gouvernerat',
                    'numero',
                    'description',
                    'email',
                    'latitude',
                    'longitude',
                ],
                'columnName' => [
                    1 => 'id_service',
                    'nom',
                    'type',
                    'heure_ouverture',
                    'heure_fermeture',
                    'prix',
                    'gouvernerat',
                    'numero',
                    'description',
                    'email',
                    'latitude',
                    'longitude',
                ],
                'length' => [
                    2 => 100,
                    50,
                    255,
                    255,
                    7 => 20,
                    9 => 255,
                    255,
                ],
                'fetch' => [
                    13 => 2,
                    2,
                    2,
                ],
                'sourceEntity' => [
                    13 => 'App\\Entity\\Service',
                    'App\\Entity\\Service',
                    'App\\Entity\\Service',
                ],
                'mappedBy' => [
                    13 => 'id_service',
                    'id_service',
                    'service_id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    13 => 'employes',
                    'resultats',
                    'reservations',
                ],
                'targetEntity' => [
                    13 => 'App\\Entity\\Employe',
                    'App\\Entity\\Resultat',
                    'App\\Entity\\Reservation',
                ],
            ],
        ],
        $o[0],
        []
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Vehicule',
                ],
                'identifier' => [
                    [
                        'id_vehicule',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id_vehicule' => $o[1],
                        'marque' => $o[2],
                        'modele' => $o[3],
                        'immatriculation' => $o[4],
                        'type' => $o[5],
                        'couleur' => $o[6],
                        'kilometrage' => $o[7],
                        'statut' => $o[8],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_vehicule' => 'id_vehicule',
                        'marque' => 'marque',
                        'modele' => 'modele',
                        'immatriculation' => 'immatriculation',
                        'type' => 'type',
                        'couleur' => 'couleur',
                        'kilometrage' => 'kilometrage',
                        'statut' => 'statut',
                    ],
                ],
                'columnNames' => [
                    [
                        'id_vehicule' => 'id_vehicule',
                        'marque' => 'marque',
                        'modele' => 'modele',
                        'immatriculation' => 'immatriculation',
                        'type' => 'type',
                        'couleur' => 'couleur',
                        'kilometrage' => 'kilometrage',
                        'statut' => 'statut',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'vehicule',
                    ],
                ],
                'associationMappings' => [
                    [
                        'id_carte_grise' => $o[9],
                        'reservations' => $o[11],
                    ],
                ],
                'idGenerator' => [
                    $o[12],
                ],
                'name' => [
                    'App\\Entity\\Vehicule',
                    10 => 'id_carte_grise',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id_vehicule',
                    'marque',
                    'modele',
                    'immatriculation',
                    'type',
                    'couleur',
                    'kilometrage',
                    'statut',
                ],
                'columnName' => [
                    1 => 'id_vehicule',
                    'marque',
                    'modele',
                    'immatriculation',
                    'type',
                    'couleur',
                    'kilometrage',
                    'statut',
                ],
                'length' => [
                    2 => 50,
                    50,
                    20,
                    50,
                    30,
                    8 => 100,
                ],
                'fetch' => [
                    9 => 2,
                    11 => 2,
                ],
                'sourceEntity' => [
                    9 => 'App\\Entity\\Vehicule',
                    11 => 'App\\Entity\\Vehicule',
                ],
                'inversedBy' => [
                    9 => 'vehicules',
                ],
                'sourceToTargetKeyColumns' => [
                    9 => [
                        'id_carte_grise' => 'id_carte_grise',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    9 => [
                        'id_carte_grise' => 'id_carte_grise',
                    ],
                ],
                'joinColumns' => [
                    9 => [
                        $o[10],
                    ],
                ],
                'joinColumnFieldNames' => [
                    9 => [
                        'id_carte_grise' => 'id_carte_grise',
                    ],
                ],
                'unique' => [
                    10 => false,
                ],
                'onDelete' => [
                    10 => 'CASCADE',
                ],
                'nullable' => [
                    10 => true,
                ],
                'referencedColumnName' => [
                    10 => 'id_carte_grise',
                ],
                'mappedBy' => [
                    11 => 'idVehicule',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    9 => 'id_carte_grise',
                    11 => 'reservations',
                ],
                'targetEntity' => [
                    9 => 'App\\Entity\\Carte_grise',
                    11 => 'App\\Entity\\Reservation',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
