<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \App\Entity\Reservation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date_reservation' => [parent::class, 'date_reservation', null],
        "\0".parent::class."\0".'heureReservation' => [parent::class, 'heureReservation', null],
        "\0".parent::class."\0".'idVehicule' => [parent::class, 'idVehicule', null],
        "\0".parent::class."\0".'id_reservation' => [parent::class, 'id_reservation', null],
        "\0".parent::class."\0".'paiements' => [parent::class, 'paiements', null],
        "\0".parent::class."\0".'service_id' => [parent::class, 'service_id', null],
        "\0".parent::class."\0".'user_id' => [parent::class, 'user_id', null],
        'date_reservation' => [parent::class, 'date_reservation', null],
        'heureReservation' => [parent::class, 'heureReservation', null],
        'idVehicule' => [parent::class, 'idVehicule', null],
        'id_reservation' => [parent::class, 'id_reservation', null],
        'paiements' => [parent::class, 'paiements', null],
        'service_id' => [parent::class, 'service_id', null],
        'user_id' => [parent::class, 'user_id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
