<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Resultat extends \App\Entity\Resultat implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'carrosorie' => [parent::class, 'carrosorie', null, 16],
        "\0".parent::class."\0".'direction' => [parent::class, 'direction', null, 16],
        "\0".parent::class."\0".'echappement' => [parent::class, 'echappement', null, 16],
        "\0".parent::class."\0".'eclairage' => [parent::class, 'eclairage', null, 16],
        "\0".parent::class."\0".'freinage' => [parent::class, 'freinage', null, 16],
        "\0".parent::class."\0".'huileDefault' => [parent::class, 'huileDefault', null, 16],
        "\0".parent::class."\0".'id_paiement' => [parent::class, 'id_paiement', null, 16],
        "\0".parent::class."\0".'id_resultat' => [parent::class, 'id_resultat', null, 16],
        "\0".parent::class."\0".'id_service' => [parent::class, 'id_service', null, 16],
        "\0".parent::class."\0".'pneaumatique' => [parent::class, 'pneaumatique', null, 16],
        "\0".parent::class."\0".'rapports' => [parent::class, 'rapports', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'vinSaisie' => [parent::class, 'vinSaisie', null, 16],
        "\0".parent::class."\0".'visibilite' => [parent::class, 'visibilite', null, 16],
        'carrosorie' => [parent::class, 'carrosorie', null, 16],
        'direction' => [parent::class, 'direction', null, 16],
        'echappement' => [parent::class, 'echappement', null, 16],
        'eclairage' => [parent::class, 'eclairage', null, 16],
        'freinage' => [parent::class, 'freinage', null, 16],
        'huileDefault' => [parent::class, 'huileDefault', null, 16],
        'id_paiement' => [parent::class, 'id_paiement', null, 16],
        'id_resultat' => [parent::class, 'id_resultat', null, 16],
        'id_service' => [parent::class, 'id_service', null, 16],
        'pneaumatique' => [parent::class, 'pneaumatique', null, 16],
        'rapports' => [parent::class, 'rapports', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'vinSaisie' => [parent::class, 'vinSaisie', null, 16],
        'visibilite' => [parent::class, 'visibilite', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
