<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Service extends \App\Entity\Service implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'employes' => [parent::class, 'employes', null, 16],
        "\0".parent::class."\0".'gouvernerat' => [parent::class, 'gouvernerat', null, 16],
        "\0".parent::class."\0".'heureFermeture' => [parent::class, 'heureFermeture', null, 16],
        "\0".parent::class."\0".'heureOuverture' => [parent::class, 'heureOuverture', null, 16],
        "\0".parent::class."\0".'idService' => [parent::class, 'idService', null, 16],
        "\0".parent::class."\0".'latitude' => [parent::class, 'latitude', null, 16],
        "\0".parent::class."\0".'longitude' => [parent::class, 'longitude', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'numero' => [parent::class, 'numero', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        "\0".parent::class."\0".'resultats' => [parent::class, 'resultats', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'employes' => [parent::class, 'employes', null, 16],
        'gouvernerat' => [parent::class, 'gouvernerat', null, 16],
        'heureFermeture' => [parent::class, 'heureFermeture', null, 16],
        'heureOuverture' => [parent::class, 'heureOuverture', null, 16],
        'idService' => [parent::class, 'idService', null, 16],
        'latitude' => [parent::class, 'latitude', null, 16],
        'longitude' => [parent::class, 'longitude', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'numero' => [parent::class, 'numero', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
        'resultats' => [parent::class, 'resultats', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
