<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employe extends \App\Entity\Employe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'age' => [parent::class, 'age', null, 16],
        "\0".parent::class."\0".'dateEmbauche' => [parent::class, 'dateEmbauche', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'equipements' => [parent::class, 'equipements', null, 16],
        "\0".parent::class."\0".'idEmploye' => [parent::class, 'idEmploye', null, 16],
        "\0".parent::class."\0".'idService' => [parent::class, 'idService', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'poste' => [parent::class, 'poste', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'salaire' => [parent::class, 'salaire', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'tel' => [parent::class, 'tel', null, 16],
        'age' => [parent::class, 'age', null, 16],
        'dateEmbauche' => [parent::class, 'dateEmbauche', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'equipements' => [parent::class, 'equipements', null, 16],
        'idEmploye' => [parent::class, 'idEmploye', null, 16],
        'idService' => [parent::class, 'idService', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'poste' => [parent::class, 'poste', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'salaire' => [parent::class, 'salaire', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'tel' => [parent::class, 'tel', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
