<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paiement extends \App\Entity\Paiement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cvc' => [parent::class, 'cvc', null],
        "\0".parent::class."\0".'date_expiration' => [parent::class, 'date_expiration', null],
        "\0".parent::class."\0".'date_paiement' => [parent::class, 'date_paiement', null],
        "\0".parent::class."\0".'id_paiement' => [parent::class, 'id_paiement', null],
        "\0".parent::class."\0".'id_reservation' => [parent::class, 'id_reservation', null],
        "\0".parent::class."\0".'nom_titulaire_carte' => [parent::class, 'nom_titulaire_carte', null],
        "\0".parent::class."\0".'numeroCarte' => [parent::class, 'numeroCarte', null],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null],
        "\0".parent::class."\0".'resultats' => [parent::class, 'resultats', null],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        'cvc' => [parent::class, 'cvc', null],
        'date_expiration' => [parent::class, 'date_expiration', null],
        'date_paiement' => [parent::class, 'date_paiement', null],
        'id_paiement' => [parent::class, 'id_paiement', null],
        'id_reservation' => [parent::class, 'id_reservation', null],
        'nom_titulaire_carte' => [parent::class, 'nom_titulaire_carte', null],
        'numeroCarte' => [parent::class, 'numeroCarte', null],
        'prix' => [parent::class, 'prix', null],
        'resultats' => [parent::class, 'resultats', null],
        'statut' => [parent::class, 'statut', null],
        'telephone' => [parent::class, 'telephone', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
