<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Carte_grise extends \App\Entity\Carte_grise implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse_proprietaire' => [parent::class, 'adresse_proprietaire', null],
        "\0".parent::class."\0".'date_emission' => [parent::class, 'date_emission', null],
        "\0".parent::class."\0".'date_expiration' => [parent::class, 'date_expiration', null],
        "\0".parent::class."\0".'id_carte_grise' => [parent::class, 'id_carte_grise', null],
        "\0".parent::class."\0".'id_user' => [parent::class, 'id_user', null],
        "\0".parent::class."\0".'numero_carte_grise' => [parent::class, 'numero_carte_grise', null],
        "\0".parent::class."\0".'proprietaire' => [parent::class, 'proprietaire', null],
        "\0".parent::class."\0".'vehicules' => [parent::class, 'vehicules', null],
        'adresse_proprietaire' => [parent::class, 'adresse_proprietaire', null],
        'date_emission' => [parent::class, 'date_emission', null],
        'date_expiration' => [parent::class, 'date_expiration', null],
        'id_carte_grise' => [parent::class, 'id_carte_grise', null],
        'id_user' => [parent::class, 'id_user', null],
        'numero_carte_grise' => [parent::class, 'numero_carte_grise', null],
        'proprietaire' => [parent::class, 'proprietaire', null],
        'vehicules' => [parent::class, 'vehicules', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
