<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipement extends \App\Entity\Equipement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'employe' => [parent::class, 'employe', null, 16],
        "\0".parent::class."\0".'etat' => [parent::class, 'etat', null, 16],
        "\0".parent::class."\0".'idEquipement' => [parent::class, 'idEquipement', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'employe' => [parent::class, 'employe', null, 16],
        'etat' => [parent::class, 'etat', null, 16],
        'idEquipement' => [parent::class, 'idEquipement', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
