<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Permis extends \App\Entity\Permis implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'date_delivrance' => [parent::class, 'date_delivrance', null, 16],
        "\0".parent::class."\0".'date_expiration' => [parent::class, 'date_expiration', null, 16],
        "\0".parent::class."\0".'etat' => [parent::class, 'etat', null, 16],
        "\0".parent::class."\0".'idQuiz' => [parent::class, 'idQuiz', null, 16],
        "\0".parent::class."\0".'id_employe' => [parent::class, 'id_employe', null, 16],
        "\0".parent::class."\0".'id_permis' => [parent::class, 'id_permis', null, 16],
        "\0".parent::class."\0".'id_service' => [parent::class, 'id_service', null, 16],
        "\0".parent::class."\0".'isRenewal' => [parent::class, 'isRenewal', null, 16],
        "\0".parent::class."\0".'numero_permis' => [parent::class, 'numero_permis', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'date_delivrance' => [parent::class, 'date_delivrance', null, 16],
        'date_expiration' => [parent::class, 'date_expiration', null, 16],
        'etat' => [parent::class, 'etat', null, 16],
        'idQuiz' => [parent::class, 'idQuiz', null, 16],
        'id_employe' => [parent::class, 'id_employe', null, 16],
        'id_permis' => [parent::class, 'id_permis', null, 16],
        'id_service' => [parent::class, 'id_service', null, 16],
        'isRenewal' => [parent::class, 'isRenewal', null, 16],
        'numero_permis' => [parent::class, 'numero_permis', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
