<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU8tscJF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU8tscJF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU8tscJF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU8tscJF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU8tscJF\App_KernelDevDebugContainer([
    'container.build_hash' => 'U8tscJF',
    'container.build_id' => '7da42e18',
    'container.build_time' => 1744718574,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU8tscJF');
