<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGw9LzRP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGw9LzRP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGw9LzRP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGw9LzRP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGw9LzRP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gw9LzRP',
    'container.build_id' => 'e138b1ec',
    'container.build_time' => 1744368378,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGw9LzRP');
