<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRVQ4Xd5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRVQ4Xd5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRVQ4Xd5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRVQ4Xd5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRVQ4Xd5\App_KernelDevDebugContainer([
    'container.build_hash' => 'RVQ4Xd5',
    'container.build_id' => '4233e82c',
    'container.build_time' => 1745931025,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRVQ4Xd5');
