<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Rapport extends \App\Entity\Rapport implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'carrosorie' => [parent::class, 'carrosorie', null],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'direction' => [parent::class, 'direction', null],
        "\0".parent::class."\0".'echappement' => [parent::class, 'echappement', null],
        "\0".parent::class."\0".'eclairage' => [parent::class, 'eclairage', null],
        "\0".parent::class."\0".'freinage' => [parent::class, 'freinage', null],
        "\0".parent::class."\0".'huileDefault' => [parent::class, 'huileDefault', null],
        "\0".parent::class."\0".'id_rapport' => [parent::class, 'id_rapport', null],
        "\0".parent::class."\0".'id_resultat' => [parent::class, 'id_resultat', null],
        "\0".parent::class."\0".'pneaumatique' => [parent::class, 'pneaumatique', null],
        "\0".parent::class."\0".'visibilite' => [parent::class, 'visibilite', null],
        'carrosorie' => [parent::class, 'carrosorie', null],
        'date' => [parent::class, 'date', null],
        'direction' => [parent::class, 'direction', null],
        'echappement' => [parent::class, 'echappement', null],
        'eclairage' => [parent::class, 'eclairage', null],
        'freinage' => [parent::class, 'freinage', null],
        'huileDefault' => [parent::class, 'huileDefault', null],
        'id_rapport' => [parent::class, 'id_rapport', null],
        'id_resultat' => [parent::class, 'id_resultat', null],
        'pneaumatique' => [parent::class, 'pneaumatique', null],
        'visibilite' => [parent::class, 'visibilite', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
